<?php
/**
 * ACF Free Field Group: About Us Page
 * 
 * Register ACF Free compatible fields with Tabs organization.
 * All field labels and instructions are i18n ready.
 * 
 * @package Wataco
 */

if (!function_exists('acf_add_local_field_group')) {
    return;
}

acf_add_local_field_group([
    'key'      => 'group_about_us_page',
    'title'    => __('About Us Page', 'wataco'),
    'fields'   => [
        // TAB: Mission Section
        [
            'key'               => 'field_mission_tab',
            'name'              => 'mission_tab',
            'label'             => __('Mission Section', 'wataco'),
            'type'              => 'tab',
            'placement'         => 'top',
            'endpoint'          => false,
        ],
        [
            'key'               => 'field_mission_section_title',
            'name'              => 'mission_section_title',
            'label'             => __('Section Title', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Main title for Vision & Mission section (fallback: "Strategic Direction")', 'wataco'),
            'default_value'     => __('Strategic Direction', 'wataco'),
            'placeholder'       => __('Strategic Direction', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_vision_title',
            'name'              => 'mission_vision_title',
            'label'             => __('Vision Title', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Fallback: "Vision"', 'wataco'),
            'default_value'     => __('Vision', 'wataco'),
            'placeholder'       => __('Vision', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_vision_desc',
            'name'              => 'mission_vision_desc',
            'label'             => __('Vision Description', 'wataco'),
            'type'              => 'textarea',
            'instructions'      => __('Vision statement content', 'wataco'),
            'placeholder'       => __('Enter vision description...', 'wataco'),
            'rows'              => 4,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_mission_title',
            'name'              => 'mission_mission_title',
            'label'             => __('Mission Title', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Fallback: "Mission"', 'wataco'),
            'default_value'     => __('Mission', 'wataco'),
            'placeholder'       => __('Mission', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_mission_desc',
            'name'              => 'mission_mission_desc',
            'label'             => __('Mission Description', 'wataco'),
            'type'              => 'textarea',
            'instructions'      => __('Mission statement content', 'wataco'),
            'placeholder'       => __('Enter mission description...', 'wataco'),
            'rows'              => 4,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_values_title',
            'name'              => 'mission_core_values_title',
            'label'             => __('Core Values Title', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Fallback: "Core Values"', 'wataco'),
            'default_value'     => __('Core Values', 'wataco'),
            'placeholder'       => __('Core Values', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_1',
            'name'              => 'mission_core_value_1',
            'label'             => __('Core Value 1', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_2',
            'name'              => 'mission_core_value_2',
            'label'             => __('Core Value 2', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_3',
            'name'              => 'mission_core_value_3',
            'label'             => __('Core Value 3', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_4',
            'name'              => 'mission_core_value_4',
            'label'             => __('Core Value 4', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_5',
            'name'              => 'mission_core_value_5',
            'label'             => __('Core Value 5', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_mission_core_value_6',
            'name'              => 'mission_core_value_6',
            'label'             => __('Core Value 6', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Enter value...', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],

        // TAB: Culture Gallery Section
        [
            'key'               => 'field_culture_tab',
            'name'              => 'culture_tab',
            'label'             => __('Culture Gallery', 'wataco'),
            'type'              => 'tab',
            'placement'         => 'top',
            'endpoint'          => false,
        ],
        [
            'key'               => 'field_culture_subtitle',
            'name'              => 'culture_subtitle',
            'label'             => __('Subtitle', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Green label above title (fallback: "Working Environment")', 'wataco'),
            'default_value'     => __('Working Environment', 'wataco'),
            'placeholder'       => __('Working Environment', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_title',
            'name'              => 'culture_title',
            'label'             => __('Title', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Main gallery title (fallback: "Life Rhythm At WATACO")', 'wataco'),
            'default_value'     => __('Life Rhythm At WATACO', 'wataco'),
            'placeholder'       => __('Life Rhythm At WATACO', 'wataco'),
            'maxlength'         => 150,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_description',
            'name'              => 'culture_description',
            'label'             => __('Description', 'wataco'),
            'type'              => 'textarea',
            'instructions'      => __('Gallery description text', 'wataco'),
            'placeholder'       => __('Enter gallery description...', 'wataco'),
            'rows'              => 3,
            'required'          => false,
        ],

        // Gallery Items (Incremental Fields for ACF Free)
        [
            'key'               => 'field_culture_item_1_title',
            'name'              => 'culture_item_1_title',
            'label'             => __('Item 1 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Team Building', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_1_category',
            'name'              => 'culture_item_1_category',
            'label'             => __('Item 1 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Team Bonding', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_1_image',
            'name'              => 'culture_item_1_image',
            'label'             => __('Item 1 - Image', 'wataco'),
            'type'              => 'image',
            'instructions'      => __('Select image (will return Image ID for CDN plugin)', 'wataco'),
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_1_span',
            'name'              => 'culture_item_1_span',
            'label'             => __('Item 1 - Grid Span', 'wataco'),
            'type'              => 'text',
            'instructions'      => __('Tailwind classes: e.g., "md:col-span-2 md:row-span-2"', 'wataco'),
            'default_value'     => 'md:col-span-2 md:row-span-2',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],

        // Item 2
        [
            'key'               => 'field_culture_item_2_title',
            'name'              => 'culture_item_2_title',
            'label'             => __('Item 2 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Site Supervision', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_2_category',
            'name'              => 'culture_item_2_category',
            'label'             => __('Item 2 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Work Environment', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_2_image',
            'name'              => 'culture_item_2_image',
            'label'             => __('Item 2 - Image', 'wataco'),
            'type'              => 'image',
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_2_span',
            'name'              => 'culture_item_2_span',
            'label'             => __('Item 2 - Grid Span', 'wataco'),
            'type'              => 'text',
            'default_value'     => 'md:col-span-1 md:row-span-1',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],

        // Item 3
        [
            'key'               => 'field_culture_item_3_title',
            'name'              => 'culture_item_3_title',
            'label'             => __('Item 3 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Internal Training', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_3_category',
            'name'              => 'culture_item_3_category',
            'label'             => __('Item 3 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Development', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_3_image',
            'name'              => 'culture_item_3_image',
            'label'             => __('Item 3 - Image', 'wataco'),
            'type'              => 'image',
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_3_span',
            'name'              => 'culture_item_3_span',
            'label'             => __('Item 3 - Grid Span', 'wataco'),
            'type'              => 'text',
            'default_value'     => 'md:col-span-1 md:row-span-1',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],

        // Item 4
        [
            'key'               => 'field_culture_item_4_title',
            'name'              => 'culture_item_4_title',
            'label'             => __('Item 4 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Strategy Meeting', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_4_category',
            'name'              => 'culture_item_4_category',
            'label'             => __('Item 4 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Planning', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_4_image',
            'name'              => 'culture_item_4_image',
            'label'             => __('Item 4 - Image', 'wataco'),
            'type'              => 'image',
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_4_span',
            'name'              => 'culture_item_4_span',
            'label'             => __('Item 4 - Grid Span', 'wataco'),
            'type'              => 'text',
            'default_value'     => 'md:col-span-1 md:row-span-2',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],

        // Item 5
        [
            'key'               => 'field_culture_item_5_title',
            'name'              => 'culture_item_5_title',
            'label'             => __('Item 5 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Item 5', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_5_category',
            'name'              => 'culture_item_5_category',
            'label'             => __('Item 5 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('Category', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_5_image',
            'name'              => 'culture_item_5_image',
            'label'             => __('Item 5 - Image', 'wataco'),
            'type'              => 'image',
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_5_span',
            'name'              => 'culture_item_5_span',
            'label'             => __('Item 5 - Grid Span', 'wataco'),
            'type'              => 'text',
            'default_value'     => 'md:col-span-1 md:row-span-1',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],

        // Item 6
        [
            'key'               => 'field_culture_item_6_title',
            'name'              => 'culture_item_6_title',
            'label'             => __('Item 6 - Title', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Sport Activities', 'wataco'),
            'maxlength'         => 100,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_6_category',
            'name'              => 'culture_item_6_category',
            'label'             => __('Item 6 - Category', 'wataco'),
            'type'              => 'text',
            'placeholder'       => __('e.g., Recreation', 'wataco'),
            'maxlength'         => 50,
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_6_image',
            'name'              => 'culture_item_6_image',
            'label'             => __('Item 6 - Image', 'wataco'),
            'type'              => 'image',
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'required'          => false,
        ],
        [
            'key'               => 'field_culture_item_6_span',
            'name'              => 'culture_item_6_span',
            'label'             => __('Item 6 - Grid Span', 'wataco'),
            'type'              => 'text',
            'default_value'     => 'md:col-span-2 md:row-span-2',
            'placeholder'       => 'md:col-span-1 md:row-span-1',
            'maxlength'         => 50,
            'required'          => false,
        ],
    ],
    'location'  => [
        [
            [
                'param'    => 'post_type',
                'operator' => '==',
                'value'    => 'page',
            ],
            [
                'param'    => 'page_template',
                'operator' => '==',
                'value'    => 'template-about-us.php',
            ],
        ],
    ],
    'menu_order'     => 0,
    'position'       => 'normal',
    'style'          => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => [],
    'active'         => true,
    'description'    => __('ACF Free fields for About Us page with Mission and Culture sections', 'wataco'),
]);
